AWSTemplateFormatVersion: '2010-09-09'
Description: 'Template to declare load balancer listerner'
Parameters:
  Stage:
    Type: String
    Description: Environment
  LoadBalancerArn:
    Type: String
    Description: Arn of the Load Balancer
  CertificateArn:
    Type: String
    Description: Arn of certificate

Resources:
  ElasticLoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
          - Type: fixed-response
            FixedResponseConfig:
              StatusCode: 200
      LoadBalancerArn: !Ref LoadBalancerArn
      Port: 80
      Protocol: HTTP

  ElasticLoadBalancerListenerHTTPS:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
          - Type: fixed-response
            FixedResponseConfig:
              StatusCode: 404
      LoadBalancerArn: !Ref LoadBalancerArn
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref CertificateArn