AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Stage:
    Type: String
    Description: Envrionment
  RdsName:
    Type: String
    Description: Name of database
Resources:
  RdsStartStopLambdaFunction:
    Type: AWS::Lambda::Function
    Properties: 
      Code: 
        ZipFile: |
            var AWS = require('aws-sdk');
            exports.handler = (event, context, callback) => {
                event.instances.forEach((instance) => {
                    switch(event.action) {
                        case 'stop':
                            console.log(`Stopping instance '${instance}'...`);
                            stopInstance(instance);
                            break;
                        case 'start':
                            console.log(`Starting instance '${instance}'...`);
                            startInstance(instance);
                            break;
                        default:
                            throw `Invalid action ${event.action}`;
                    }
                })
                callback(null, 'Done!');
            };

            const stopInstance = (instanceId) => {
                var rds = new AWS.RDS();
                var today = new Date();
                var params = {
                  DBInstanceIdentifier: instanceId, 
                  DBSnapshotIdentifier: `${instanceId}-${today.getDate()}-${today.getMonth()+1}-${today.getFullYear()}-${today.getTime()}`
                };
                rds.stopDBInstance(params, function(err, data) {
                  if (err) console.log(err, err.stack); // an error occurred
                  else     console.log(data);           // successful response
                });
            };

            const startInstance = (instanceId) => {
                var rds = new AWS.RDS();
                var params = {
                  DBInstanceIdentifier: instanceId
                };
                rds.startDBInstance(params, function(err, data) {
                  if (err) console.log(err, err.stack); // an error occurred
                  else     console.log(data);           // successful response
                });
            };
      Handler: index.handler
      Description: Lambda Function to Start and Stop RDS
      FunctionName: !Sub ${Stage}-StartStopRds
      Role: !GetAtt LambdaRdsStartStopRole.Arn
      Runtime: nodejs12.x

  CloudWatchStartRule:
    Type: AWS::Events::Rule
    Properties: 
      Description: Cloud Watch Rule to start the database
      Name: !Sub ${Stage}-rds-start
      ScheduleExpression: cron(50 9 ? * MON-FRI *)
      State: ENABLED
      Targets: 
        - Arn:
            Fn::GetAtt:
              - "RdsStartStopLambdaFunction"
              - "Arn"
          Id: !Sub ${Stage}-StartStopRds
          Input: !Sub '{ "instances": ["${RdsName}"], "action":"start" }'

  CloudWatchStopRule:
    Type: AWS::Events::Rule
    Properties: 
      Description: Cloud Watch Rule to stop the database
      Name: !Sub ${Stage}-rds-stop
      ScheduleExpression: cron(0 22 ? * MON-FRI *)
      State: ENABLED
      Targets: 
        - Arn:
            Fn::GetAtt:
              - "RdsStartStopLambdaFunction"
              - "Arn"
          Id:  !Sub ${Stage}-StartStopRds
          Input: !Sub '{ "instances": ["${RdsName}"], "action":"stop" }'

  PermissionForStartEventsToInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !Sub ${Stage}-StartStopRds
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: 
        Fn::GetAtt: 
          - "CloudWatchStartRule"
          - "Arn"

  PermissionForStopEventsToInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !Sub ${Stage}-StartStopRds
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: 
        Fn::GetAtt: 
          - "CloudWatchStopRule"
          - "Arn"

  LambdaRdsStartStopRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - rds.amazonaws.com
                - lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: "lambda-rds-start-stop"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - 
                Action:
                  - 'rds:StopDBInstance'
                  - 'rds:StartDBInstance'
                Resource: '*'
                Effect: Allow
      RoleName: !Sub '${Stage}-LambdaRdsStartStop'